In [5]:
import cv2
import numpy as np

# Read the image
image = cv2.imread('12.png')

# Display the result
cv2.imshow('White Portion', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


100.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# without  set extra width and height 

In [36]:
import cv2

# Read the image
image = cv2.imread('12.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Threshold the image to create a binary image
_, thresholded = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)

# Find contours in the binary image
contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Find the largest contour
largest_contour = max(contours, key=cv2.contourArea)

# Get the bounding box of the largest contour
x, y, w, h = cv2.boundingRect(largest_contour)

# Crop the marked portion from the original image
cropped_image = image[y:y+h, x:x+w]

# Save the cropped image
cv2.imwrite('crop_1.png', cropped_image)

# Display the cropped image
cv2.imshow('Cropped Image', cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


# set extra width and height 

In [35]:
# set new hight and width , added up extra
import cv2

# Read the image
image = cv2.imread('12.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Threshold the image to create a binary image
_, thresholded = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)

# Find contours in the binary image
contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Find the largest contour
largest_contour = max(contours, key=cv2.contourArea)

# Get the bounding box of the largest contour
x, y, w, h = cv2.boundingRect(largest_contour)

# Increase the size of the bounding rectangle by 1% of width and height
padding_percentage = 1.01
new_x = int(x - w * (padding_percentage - 1) / 2)
new_y = int(y - h * (padding_percentage - 1) / 2)
new_w = int(w * padding_percentage)
new_h = int(h * padding_percentage)

# Ensure the new coordinates and dimensions are within the image boundaries
new_x = max(0, new_x)
new_y = max(0, new_y)
new_w = min(image.shape[1] - new_x, new_w)
new_h = min(image.shape[0] - new_y, new_h)

# Crop the marked portion from the original image
cropped_image = image[new_y:new_y+new_h, new_x:new_x+new_w]

# Save the cropped image
cv2.imwrite('cr12.png', cropped_image)

# Display the cropped image
cv2.imshow('Cropped Image', cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Multiple images - test baki 

In [ ]:
import cv2
import os

def process_image(input_path):
    # Read the image
    image = cv2.imread(input_path)
    
    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Threshold the image to create a binary image
    _, thresholded = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)
    
    # Find contours in the binary image
    contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Find the largest contour
    largest_contour = max(contours, key=cv2.contourArea)
    
    # Get the bounding box of the largest contour
    x, y, w, h = cv2.boundingRect(largest_contour)
    
    # Increase the size of the bounding rectangle by 1% of width and height
    padding_percentage = 1.01
    new_x = int(x - w * (padding_percentage - 1) / 2)
    new_y = int(y - h * (padding_percentage - 1) / 2)
    new_w = int(w * padding_percentage)
    new_h = int(h * padding_percentage)
    
    # Ensure the new coordinates and dimensions are within the image boundaries
    new_x = max(0, new_x)
    new_y = max(0, new_y)
    new_w = min(image.shape[1] - new_x, new_w)
    new_h = min(image.shape[0] - new_y, new_h)
    
    # Crop the marked portion from the original image
    cropped_image = image[new_y:new_y+new_h, new_x:new_x+new_w]
    
    return cropped_image

# Path to the directory containing your images
input_directory = 'path/to/your/images'

# List to store processed images
processed_images = []

# Loop through each image in the input directory and process it
for filename in os.listdir(input_directory):
    if filename.endswith('.png') or filename.endswith('.jpg'):
        input_path = os.path.join(input_directory, filename)
        processed_image = process_image(input_path)
        processed_images.append(processed_image)

print('Processing completed.')

# Now, processed_images list contains all the reshaped images
# You can save these images or use them as needed.
