In [1]:
# some points about array


- Array can store data of specified type
- Element of array are located in a contiguous
- Each Element of an array has a unique inedx
-
-
- We use array for a collection of variable type data

## types of array
- one Dimesion
- multiple Dimension ( representing in Memory as like 1d )


In [2]:
arr = [2,3,4,5,6,90,87]

In [3]:
import array

arr = array.array('i') # O(1) - creating empty array
print(arr)

array('i')


In [4]:
import array

arr = array.array('i',[1,2,3,4,5]) # O(N) - creating non- empty array
print(arr)

array('i', [1, 2, 3, 4, 5])


In [5]:
# another away is created array is
import numpy as np
np_arr = np.array([],dtype=int) # O(1)  - creating empty array
print(np_arr)

[]


In [6]:
# another away is created array is
import numpy as np
np_arr1 = np.array([1,76,5,4,323],dtype=int) # O(N) - creating non- empty array
print(np_arr1)

[  1  76   5   4 323]


In [7]:
# Time and Space
#
# Createing and Empty array O(1)
# space complexity is O(N)

# Insert Element In Array
- start
- end
- middle ( index )

## Time and Space Compleixty
- Time => O(N)
- Space => O(1)

In [8]:
# start

import array

arr = array.array('i',[4,5,34,2,1])
print(arr)

arr.insert(0,90)
print(arr)

array('i', [4, 5, 34, 2, 1])
array('i', [90, 4, 5, 34, 2, 1])


In [9]:
# insert in any Index

arr = array.array('i',[4,5,34,2,1])
print(arr)

arr.insert(3,920)
print(arr)

array('i', [4, 5, 34, 2, 1])
array('i', [4, 5, 34, 920, 2, 1])


# Array traversal
- start a loop and print the each index is called traversal


In [10]:
from array import *

arr1 = array('i',[45,34,23,67])
arr2 = array('d',[12.34,43.2,56.7,67.54])

def traversal(array_):
  for i in array_:     # O(1)
    print(i)            # O(N)


traversal(arr1)


45
34
23
67


In [11]:
# another away traversal - index based
def traversal_v2(array,index):
  if index < len(array):  # O(1) - for any condition
    print(array[index])    # O(1) - for any condition
  else:
    print('index out of the range ')  # O(1) - for any condition


traversal_v2(arr2,4)

index out of the range 


# 34
https://colonline.udemy.com/course/data-structures-and-algorithms-bootcamp-in-python/learn/lecture/37471944#overview


## Array Practice

In [12]:
from array import *

# create and traverse array

arr1 = array('i',[45,75,72,34])

for i in arr1:
  print(i)

45
75
72
34


In [13]:
# access individual element through elements
print(arr1[3])

# 3. using append() methods

print('Append')
arr1.append(565)
arr1

34
Append


array('i', [45, 75, 72, 34, 565])

In [14]:
# 4. Insert value in Array using insert method
print('step 4')
arr1.insert(2,99)
print(arr1)

step 4
array('i', [45, 75, 99, 72, 34, 565])


In [15]:
# 5 using extend() method - to extend our array
arr2 = array('i',[100,500,300,500])
arr2.extend(arr1) # add arr1 here as a result we can see the same thing repeat in the last of 2nd array
print(arr2)

array('i', [100, 500, 300, 500, 45, 75, 99, 72, 34, 565])


In [16]:
# 6 list into array using fromList()
tempList = [20,21,23,30]
arr2.fromlist(tempList)
print(arr2)

array('i', [100, 500, 300, 500, 45, 75, 99, 72, 34, 565, 20, 21, 23, 30])


In [17]:
# 7 remove any element from array
arr2.remove(500)
print(arr2) # if the similar data available at that time first one goes to remove

array('i', [100, 300, 500, 45, 75, 99, 72, 34, 565, 20, 21, 23, 30])


In [18]:
# 8 pop() using
arr2.pop()
print(arr2)

array('i', [100, 300, 500, 45, 75, 99, 72, 34, 565, 20, 21, 23])


In [19]:
# 9 fetch any element through index()
print('step 9')
# assume 99 is a value and I do not know where it is in the large array . I can know its crossponding index number by using the index() methods
print(arr2.index(99))

step 9
5


In [20]:
# 10 reverse
print('step 10')
arr2.reverse()
arr2

step 10


array('i', [23, 21, 20, 565, 34, 72, 99, 75, 45, 500, 300, 100])

In [21]:
# 11 buffere information through the buffer_info() methods

print('step 11')
# arr2.buffer_info()
print(arr2.buffer_info())

step 11
(138756241438256, 12)


In [22]:
# 12 count method
#
# Generally count methods used for to know the total no of the elements , but here in Python it returns the no of occurances
arr2.count(99)

1

In [23]:
# 13 array to str
str1 =  str(arr2)
print(str1)


array('i', [23, 21, 20, 565, 34, 72, 99, 75, 45, 500, 300, 100])


## array operatins

In [24]:
from array import *

In [25]:
# 1 create array and traverse
my_arr = array('i',[1,2,3,4,5]) # 'i' is typecode represent int

for i in my_arr: #O(N)
  print(i)

1
2
3
4
5


In [26]:
# 2 access individual array elements through indexes
my_arr = array('i',[1,2,3,4,5]) # 'i' is typecode represent int

my_arr[0]

1

In [27]:
# 3 append any values using append() method
my_arr = array('i',[1,2,3,4,5]) # 'i' is typecode represent int

my_arr.append(33) # append element in the end of the array  O(N)
my_arr

array('i', [1, 2, 3, 4, 5, 33])

In [28]:
# 4 insert value using insert()
my_arr = array('i',[1,2,3,4,5]) # 'i' is typecode represent int

my_arr.insert(3,100)  # insert takes 2 argument first is indices and second parameter is value we can add any element of any indices

my_arr

array('i', [1, 2, 3, 100, 4, 5])

In [29]:
# 5 Extend python array using extend() method

arr = array('i',[100,200,300,400])
arr.extend([900,500]) # use can pass arr also inside the extend method arr.extend(arr)
arr

array('i', [100, 200, 300, 400, 900, 500])

In [30]:
# 6 Add items from list into array using fromList() method

tempList = [20,21,22,23] # created a temporary list which is going to add for further array

arr = array('i',[100,200,300,400])  # created an array

arr.fromlist(tempList) # using .fromlist() method and just passing the tempList over the here
arr

array('i', [100, 200, 300, 400, 20, 21, 22, 23])

In [31]:
arr

array('i', [100, 200, 300, 400, 20, 21, 22, 23])

In [32]:
# 7 Remove any element using remove()

arr.remove(400)
arr

array('i', [100, 200, 300, 20, 21, 22, 23])

In [33]:
arr.remove(300)
arr

array('i', [100, 200, 20, 21, 22, 23])

In [34]:
arr.fromlist([200,100,200])

In [35]:
# 8 remove last element using pop()
print(arr)
arr.pop()

print(arr)

array('i', [100, 200, 20, 21, 22, 23, 200, 100, 200])
array('i', [100, 200, 20, 21, 22, 23, 200, 100])


In [36]:
# 9 Fetch any element through its index using index() method
print(arr)
print('i am looking 23 where in array')
arr.index(23) # return index number

array('i', [100, 200, 20, 21, 22, 23, 200, 100])
i am looking 23 where in array


5

In [37]:
# 10 reverse a arr
arr.pop()
print(arr)
arr.reverse( )
print(arr)

array('i', [100, 200, 20, 21, 22, 23, 200])
array('i', [200, 23, 22, 21, 20, 200, 100])


In [38]:
# 11 Get array buffer information through buffer_info() method
print(arr.buffer_info()) # return memory address and no of element

(138756241708384, 7)


In [39]:
# 12 no of occurance of an element using count
arr.count(200) # return the no of occurance . in array count() works different compare to the other methods

2

In [40]:
# 13 convert array to String using tobytes()

arr = array('i',[100,200,300,400])

print(arr)

str_temp = arr.tobytes()

print(str_temp) # convert array to bytes ( unread able format)

ints = array('i') # create a int array without any values

ints.frombytes(arr.tobytes())  # readable format bytes to array

print(ints)

array('i', [100, 200, 300, 400])
b'd\x00\x00\x00\xc8\x00\x00\x00,\x01\x00\x00\x90\x01\x00\x00'
array('i', [100, 200, 300, 400])


In [41]:
# 14 append a string to char array using fromstring() method


## 2D array

In [42]:
# create
import numpy as np
towD= np.array([[1,2,6],[4,5,9],[5,9,8]]) # O(MN)

In [43]:
print(towD)

[[1 2 6]
 [4 5 9]
 [5 9 8]]


In [44]:
# insest in 2D array
# addition column or row


In [45]:
# adding rows  using insert()

new2D = np.insert(towD,0,[[99,88,77]],axis=0) # oldArray , position(index),values , axis = 0 ( row ) and 1 for column
print(new2D)

[[99 88 77]
 [ 1  2  6]
 [ 4  5  9]
 [ 5  9  8]]


In [46]:
new2D = np.insert(towD,2,[[99,88,77]],axis=1) # oldArray , position(index),values , axis = 0 ( row ) and 1 for column
print(new2D)

[[ 1  2 99  6]
 [ 4  5 88  9]
 [ 5  9 77  8]]


In [47]:
# using append() method
# new2D = np.append(towD,[[999,988,977]],axis=0) # oldArray , position(index),values , axis = 0 ( row ) and 1 for column
# print(new2D)

In [48]:
towD = np.array([[1,2,6],[4,5,9],[5,9,8]])
new_column = np.array([[999],[988],[977]]) # reshaped to 3x1
new2D = np.append(towD, new_column ,axis=1)
print(new2D)


[[  1   2   6 999]
 [  4   5   9 988]
 [  5   9   8 977]]


In [49]:
# access 2D array

towD[2][2]

8

In [50]:
def accessElement(array,rowIndex,colIndex):
  if rowIndex >= len(array) and colIndex>=len(array[0]):
    print('In correct index')
  else:
    print(array[rowIndex][colIndex])

In [51]:
accessElement(towD,4,5)

In correct index


In [52]:
# Traversing 2D array
def traverse2D(array):
  for i in range(len(array)): # O (mn)
    for j in range(len(array[0])): # O(n)
      print(array[i][j]) # O(1)
    print(' one row don')

traverse2D(towD)

1
2
6
 one row don
4
5
9
 one row don
5
9
8
 one row don


In [53]:
# Searching Two D array
def search(array,value):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j]==value:
        return print(f'value find at index {i} {j}')

  return 'no value '


In [54]:
towD2 = np.array([[1,2,6],[4,50,9],[5,9,8]])
search(towD2,50)

value find at index 1 1
