In [15]:
from array import *

arr1 = array('i',[45,34,23,67])
arr2 = array('d',[12.34,43.2,56.7,67.54])

def traversal(array_):
  for i in array_:     # O(1)
    print(i)            # O(N)


traversal(arr1)


45
34
23
67


In [16]:
# create
import numpy as np
towD= np.array([[1,2,6],[4,5,9],[5,9,8]]) # O(MN)

In [17]:
new2D = np.insert(towD,0,[[99,88,77]],axis=0) # oldArray , position(index),values , axis = 0 ( row ) and 1 for column
print(new2D)

new2D = np.insert(towD,2,[[99,88,77]],axis=1) # oldArray , position(index),values , axis = 0 ( row ) and 1 for column
print(new2D)

[[99 88 77]
 [ 1  2  6]
 [ 4  5  9]
 [ 5  9  8]]
[[ 1  2 99  6]
 [ 4  5 88  9]
 [ 5  9 77  8]]


In [18]:
towD = np.array([[1,2,6],[4,5,9],[5,9,8]])
new_column = np.array([[999],[988],[977]]) # reshaped to 3x1
new2D = np.append(towD, new_column ,axis=1)
print(new2D)


[[  1   2   6 999]
 [  4   5   9 988]
 [  5   9   8 977]]


In [19]:
def accessElement(array,rowIndex,colIndex):
  if rowIndex >= len(array) and colIndex>=len(array[0]):
    print('In correct index')
  else:
    print(array[rowIndex][colIndex])

In [20]:
# Traversing 2D array
def traverse2D(array):
  for i in range(len(array)): # O (mn)
    for j in range(len(array[0])): # O(n)
      print(array[i][j]) # O(1)
    print(' one row don')

traverse2D(towD)

1
2
6
 one row don
4
5
9
 one row don
5
9
8
 one row don


In [23]:
# Searching Two D array
def search(array,value):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j]==value:
        return print(f'value find at index i = [{i}][{j}]')

  return 'no value '

towD = np.array([[1,2,6],[4,50,9],[5,9,8]])
search(towD,50)

value find at index i = [1][1]
