In [3]:
import cv2 as cv
import numpy as np

In [4]:
cv.__version__

'4.7.0'

# Read and Write image File
- imread() for read a image
    - imread() return BGR formet even it is Grayscale image . BGR = RGB
- imwrite() for write a image 

In [8]:
img = np.zeros((3,3),dtype=np.uint8)

In [9]:
img

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

###  image change

In [11]:
img = cv.cvtColor(img,cv.COLOR_GRAY2BGR)

In [12]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [63]:
img2 = np.ones((7,8),dtype=np.uint8)

In [64]:
img2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [65]:
img2 = cv.cvtColor(img2,cv.COLOR_GRAY2BGR)

In [66]:
img2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],


In [19]:
img2.shape

(5, 4, 3)

In [24]:
# conver image FORMAT

In [30]:
image = cv.imread('sr.jpg')

In [31]:
cv.imwrite('sre.png',image)

True

In [33]:
image.shape

(3532, 4036, 3)

## Raw bytes convert to Image 
[0,0] or [0,0,0] 
- where first is represent Y axis , '0' being the top
- 2nd one is represent X axis , '0' being the leftmost 

In [40]:
byteArray = bytearray(image)

In [42]:
# byteArray

In [44]:
import os

In [49]:
# make an array of 1,20,000 bytes array 
randomByteArray = bytearray(os.urandom(120000))

In [46]:
flatNumpyArray = np.array(randomByteArray)

In [52]:
#------------------------ Run this -------
# radnomByteArray
# flatNumpyArray

In [55]:
# now assign the shape 400 * 300 
grayImage = flatNumpyArray.reshape(300,400)

cv.imwrite('randomGrayImage.png',grayImage)

True

In [61]:
# bgr image 

bgrImage = flatNumpyArray.reshape(200,200,3)
cv.imwrite('RandomColor.png',bgrImage)

True

In [67]:
## Image data 'ACCESS' with Numpy.array

In [78]:
image2 = cv.imread('sr.jpg')

In [80]:
image2[0,0] = [255,255,255]

In [82]:
image2.shape

(3532, 4036, 3)

## setting all value ( B | G | R ) = 0

In [83]:
image2 = cv.imread('sr.jpg')

In [95]:
# sample - 01 
image = cv.imread('sr.jpg')
image[: , : , 1] = 0

In [96]:
image

array([[[65,  0, 66],
        [65,  0, 66],
        [65,  0, 66],
        ...,
        [31,  0, 35],
        [30,  0, 34],
        [30,  0, 34]],

       [[66,  0, 67],
        [65,  0, 66],
        [65,  0, 66],
        ...,
        [31,  0, 35],
        [31,  0, 35],
        [30,  0, 34]],

       [[64,  0, 67],
        [63,  0, 66],
        [65,  0, 66],
        ...,
        [32,  0, 36],
        [31,  0, 35],
        [31,  0, 35]],

       ...,

       [[37,  0, 59],
        [37,  0, 59],
        [37,  0, 59],
        ...,
        [24,  0, 31],
        [24,  0, 31],
        [24,  0, 31]],

       [[38,  0, 58],
        [38,  0, 58],
        [38,  0, 58],
        ...,
        [24,  0, 31],
        [24,  0, 31],
        [24,  0, 31]],

       [[38,  0, 58],
        [38,  0, 58],
        [37,  0, 57],
        ...,
        [24,  0, 31],
        [24,  0, 31],
        [24,  0, 31]]], dtype=uint8)

In [106]:
img2 = cv.imread('cn.png')

In [110]:
img2[:,:,1] = 0
#img2

# ROI ( Regions of Interest)
- a particular regions move to other place 

In [114]:
img = cv.imread('sr.jpg')

In [115]:
my_roi = img[0:200,0:200]

In [116]:
img[250:450, 250:450] = my_roi

In [117]:
print(img.shape) # Gray scale image len = 2 , Color Image = 3
print(img.size) 
print(img.dtype)

(3532, 4036, 3)
42765456
uint8


# R/W a video file 

In [119]:
import cv2 as cv

In [131]:
videoCapture = cv.VideoCapture('MyInputVid.avi')
fps = videoCapture.get(cv.CAP_PROP_FPS)

size = (int(videoCapture.get(cv.CAP_PROP_FRAME_WIDTH)),int(videoCapture.get(cv.CAP_PROP_FRAME_HEIGHT)))

videoWriter = cv.VideoWriter('MyOutput.avi',cv.VideoWriter_fourcc('I','4','2','0'),fps,size)


success , frame = videoCapture.read()

while success:
    videoWrite.write(frame)
    success,frame = videoCapture.read()

# Capture Camera

In [143]:
cameraCapture = cv.VideoCapture(0)

fps = 30 

size = (int(cameraCapture.get(cv.CAP_PROP_FRAME_WIDTH)),int(cameraCapture.get(cv.CAP_PROP_FRAME_HEIGHT)))

videoWriter = cv.VideoWriter('MyOutputVid.avi',cv.VideoWriter_fourcc('I','4','2','0'),fps,size)


success , frame = cameraCapture.read()

control_loop = 10 * fps - 1 

while success and control_loop > 0:
    videoWriter.write(frame)
    success,frame = cameraCapture.read()
    control_loop -= 1

 
# Display Image 

In [3]:
 import cv2 as cv 
    
ima = cv.imread('sr.png')
cv.imshow('my image',ima)
cv.waitKey()
cv.destroyAllWindows()

In [4]:
# the image is too large so reshape the size of the IMAGE
# the The Original Dimensions :  (3532, 4036, 3)

img = cv.imread('sr.png', cv.IMREAD_UNCHANGED)
 
print('Original Dimensions ( shape )  : ',img.shape)
 
scale_percent = 10 # percent of original size

width = int(img.shape[1] * scale_percent / 100)

height = int(img.shape[0] * scale_percent / 100)

dim = (width, height)
  
# resize image
resized = cv.resize(img, dim, interpolation = cv.INTER_AREA)

# save resized image 

cv.imwrite('resajjad.png',resized)

print('Resized Dimensions : ',resized.shape)
 
cv.imshow("Resized image", resized)
cv.waitKey(0)
cv.destroyAllWindows()

Original Dimensions ( shape )  :  (3532, 4036, 3)
Resized Dimensions :  (353, 403, 3)


# Display Camera Frames in Window

In [7]:
clicked = False

def onMouse(event,x,y,flags,param):
    global clicked
    if event == cv.EVENT_LBUTTONUP:
        clicked = True

cameraCapture = cv.VideoCapture(0)
cv.namedWindow('my window')
cv.setMouseCallback('my window',onMouse)

print('window or any key to stop ')

success , frame = cameraCapture.read()

while success and cv.waitKey(1)==-1 and not clicked:
    cv.imshow('my window',frame)
    success,frame = cameraCapture.read()
    
cv.destroyAllWindows()
cameraCapture.release()

window or any key to stop 


# Project Cameo 

In [8]:
import cv2 as cv
import numpy as np
import time 

In [13]:
class CaptureManager(object):
    def __init__(self,capture,previewWindow = None , shouldMirrorPreview=False):
        self.previewWindowManager = previewManager
        self.shouldMirrorPreview = shouldMirrorPreview
        self._capture = capture
        self._channel=0
        self._enteredFrame = False
        self._frame = None
        self._imageFilename = None
        self._videoFilename = None
        self._videoEncoding = None
        self._videoWriter = None
        self._startTime = None
        self._framesElapsed = 0
        self._fpsEstimate = None
        
@property 
def channel(self):
    return self._channel
@channel.setter
def channel(self,value):
    if self._channel != value:
        self._channel = value
        self._frame = None

@property
def frame(self):
    if self._enteredFrame and self._frame is None:
        _,self._frame = self._captture.retrive(self._frame , self.channel)
    return self._frame 
@property

def isWritingImage(self):
    return self._imageFilename is not None
@property
def isWritingVideo(self):
    return sefl._videoFilename is not None 

def enterFrame(self):
    """ capture the next frame if any"""
    assert not self._entertedFrame,\
        'previous enterFrame() had no matching exitFrame()'
    if self._capture is not None:
        self._enteredFrame = self._capture.grab()

def exitFrame(self):
    
    if sefl.frame is None:
        self._enteredFrame = False
        return 
    # update the fps estimate time and related variables 
    
    if self._frameElapsed == 0:
        self._startTime = time.time()
    else:
        timeElapsed = time.time()
        self._fpsEstimate = self._frameElapsed/ timeElpased
    self._frameElpased += 1
    
    # draw to the window if any 
    
    if self.previewWindowManager is not None:
        if self.shouldMirrorPreview:
            mirroredFrame = numpy.fliplr(self._frame)
            self.previewWindowManager.show(mirroredFrame)
        else:
            self.previewWindowManger.show(self._frame)
    
    # write to the image file 
    if self.isWritingImage:
        cv.imwrite(self._imageFilename,self._frame)
        self._imageFilename = None
        
    self._writeVideoFrame()
    
    # Relase the frame:
    self._frame = None
    self._enteredFrame = False
    
    
    def writeImage (self,filename):
        self._imageFilename = filename
    
    def startWritingVideo(self, filename,encoding = cv2.VideoWriter_fourcc('M','J','P','G')):
        """Start writing exited frames to a video file."""
        self._videoFilename = filename
        self._videoEncoding = encoding
    
    def stopWritingVideo(self):
        """Stop writing exited frames to a video file."""
        self._videoFilename = None
        self._videoEncoding = None
        self._videoWriter = None
        
    def _writeVideoFrame(self):
        if not self.isWritingVideo:
            return
        if self._videoWriter is None:
            fps = self._capture.get(cv2.CAP_PROP_FPS)
            if fps <= 0.0:
                # The capture's FPS is unknown so use an estimate.
                if self._framesElapsed < 20:
                    # Wait until more frames elapse so that the
                    # estimate is more stable.
                    return
                else:
                    fps = self._fpsEstimate
            size = (int(self._capture.get(cv2.CAP_PROP_FRAME_WIDTH)),int(self._capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
            
            self._videoWriter = cv2.VideoWriter(self._videoFilename, self._videoEncoding,fps, size)
            
        self._videoWriter.write(self._frame)
                    
                                                                    
                                                                         
                                                           

In [ ]:
class WindowManager(object):
    # page 61 