## library import

In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import cv2

## data load from keras

In [3]:
(x_train,y_train),(x_test,y_test) = keras.datasets.cifar10.load_data()

170498071/170498071 [==============================] - 2s 0us/step


## shape

In [4]:
x_train.shape
x_test.shape

(10000, 32, 32, 3)

In [5]:
#Normalization
x_train = x_train/255.0
x_test = x_test/255.0


## image conver to 2D

In [6]:
# sklearn expects i/p to be 2d array-model.fit(x_train,y_train)=> reshape to 2d array

nsamples,nx,ny,nrgb = x_train.shape

x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [11]:
 # so , eventually model.predict() should also be a 2d input
nsamples,nx,ny,nrgb = x_test.shape

x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

In [16]:
x_test.shape

(10000, 32, 32, 3)

In [17]:
x_test2.shape

(10000, 3072)

In [20]:
x_train.shape

(50000, 32, 32, 3)

In [22]:
x_train.shape

(50000, 3072)

In [23]:
y_train.shape

(50000, 1)

# knn load

In [12]:
# KNN algorithm

from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn = KNeighborsClassifier(n_neighbors=7)

In [24]:
knn.fit(x_train2,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [25]:
y_pred_knn = knn.predict(x_test2)

In [26]:
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [27]:
score = accuracy_score(y_pred_knn,y_test)

print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



# score

In [28]:
score

0.3358

# Custome Input

In [35]:
img = cv2.imread("/content/b1.jpg")
img = cv2.resize(img,(32,32))

In [30]:
nx,ny,nrgb = img.shape
img2 = img.reshape(1,(nx*ny*nrgb))

In [31]:
classes =['airplane','automobile','bird','cat','deer','frog','horse','ship','truck']

In [32]:
result = knn.predict(img2)

In [33]:
result

array([0], dtype=uint8)

In [34]:
# the result shows that it is airplane as 'array([0], dtype=uint8)' actually it is bird . the problem occurs due to score 33% only


In [43]:
img3 = cv2.imread("/content/d1.jpg")
img3 = cv2.resize(img3,(32,32))

nx,ny,nrgb = img3.shape
img4 = img3.reshape(1,(nx*ny*nrgb))

In [44]:
result2 = knn.predict(img4)
result2

array([0], dtype=uint8)