# HPFs and LPFs

In [4]:
import cv2 as cv
import numpy as np
from scipy import ndimage

In [10]:
kernel_3x3 = np.array([
       [-1, -1, -1],
       [-1,  8, -1],
       [-1, -1, -1]])
 

In [11]:
kernel_3x3


array([[-1, -1, -1],
       [-1,  8, -1],
       [-1, -1, -1]])

In [12]:
kernel_5x5  = np.array([
       [-1, -1, -1, -1, -1],
       [-1,  1,  2,  1, -1],
       [-1,  2,  4,  2, -1],
       [-1,  1,  2,  1, -1],
       [-1, -1, -1, -1, -1]])

In [13]:
kernel_5x5

array([[-1, -1, -1, -1, -1],
       [-1,  1,  2,  1, -1],
       [-1,  2,  4,  2, -1],
       [-1,  1,  2,  1, -1],
       [-1, -1, -1, -1, -1]])

In [14]:
img = cv.imread('statue_small.jpg',0)

In [17]:
 k3 = ndimage.convolve(img,kernel_3x3)

In [18]:
 k5 = ndimage.convolve(img,kernel_5x5)

In [19]:
blurred = cv.GaussianBlur(img,(17,17),0)

In [20]:
g_hpf = img - blurred

In [30]:
cv.imshow("img",img)
cv.imshow("3x3",k3)
cv.imshow("5x5",k5)

cv.imshow("blurred",blurred)
cv.imshow("g_hpf",g_hpf)
cv.waitKey()
cv.destroyAllWindows()

-1

# Edge Detection with canny

In [31]:
import cv2 as cv
import numpy as np

In [40]:
img = cv.imread('22.jpeg',0)
cv.imwrite('canny2.jpg',cv.Canny(img,100,200))
cv.imshow("canny",cv.imread('canny2.jpg'))
cv.waitKey()
cv.destroyAllWindows()

### how cv.Canny() works : 

- Denoise the image with a Gaussian filter.1.

- Calculate the gradients.2.

- Apply non-maximum suppression (NMS) on the edges. Basically, this means3.
that the algorithm selects the best edges from a set of overlapping edges. We'll
discuss the concept of NMS in detail in Chapter 7, Building Custom Object
Detectors.

- Apply a double threshold to all the detected edges to eliminate any false4.
positives.

- Analyze all the edges and their connection to each other to keep the real edges5.
and discard the weak ones.

# Counter Detection 

In [30]:
import cv2 as cv
import numpy as np

In [31]:
img = np.zeros((200,200),dtype=np.uint8)

In [32]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [33]:
img[50:150,50:150] = 255

In [34]:
ret,thres=cv.threshold(img,127,255,0)

In [35]:
contours,heirarchy = cv.findContours(thres,cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)

- heirarchy
# findContours function. 
` This function has three parameters: the input image, the hierarchy type, and the contour approximation method `

In [36]:
color = cv.cvtColor(img,cv.COLOR_GRAY2BGR)

In [37]:
img = cv.drawContours(color,contours,-1,(0,255,0),2)

In [38]:
cv.imshow('contours',color)
cv.waitKey()
cv.destroyAllWindows()

# Bounding box, minimum area rectangle, and minimum enclosing circle

In [58]:
import cv2 as cv 
import numpy as np

In [73]:
# img = cv.pyrDown(cv.imread('enclose.png',cv.IMREAD_UNCHANGED))
img = cv.pyrDown(cv.imread('statue_small.jpg',cv.IMREAD_UNCHANGED))


In [74]:
# img

In [75]:
ret,thresh = cv.threshold(cv.cvtColor(img,cv.COLOR_BGR2GRAY),127,255,cv.THRESH_BINARY)

In [76]:
contours,hier = cv.findContours(thresh,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE)

In [77]:
# contours

In [81]:
for c in contours:
    # find bounding box coordinates
    x,y,w,h = cv.boundingRect(c)
    cv.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    
    # find minimum area 
    rect = cv.minAreaRect(c)
    
    # calculate coordinate of the minimum area rectangle 
    box = cv.boxPoints(rect)
    
    # normalize coordinate to inegers
    box = np.int0(box)
    
    # draw contours 
    cv.drawContours(img,[box],0,(0,0,255),3)
    
    # calculate center and radius of minimum enclosing circle 
    
    (x,y) , radius = cv.minEnclosingCircle(c)
    
    # cast to integers 
    center = (int(x),int(y))
    radius = int ( radius)
    
    # draw the circle 
    img = cv.circle(img,center,radius,(0,255,0),2)
    
    
#     cv.drawContours(img,contours,-1,(255,0,0),1)
#     cv.imshow("contours",img)
    
#     cv.waitKey()
#     cv.destroyAllWindows()
    


In [79]:
cv.drawContours(img,contours,-1,(255,0,0),1)
cv.imshow("contours",img)
    
cv.waitKey()
cv.destroyAllWindows()

 # Convex contours and the Douglas-Peucker algorithm