In [1]:
# Pytorch
#
# Qick Iteration
# Seamless graph model transition with TorchScript
# production ready with TorchServe
#

In [ ]:
!pip install torch torchvision -U


In [3]:
import torch

print(torch.__version__)


2.0.1+cu118


In [4]:
import torch as tor

In [5]:
t0 = tor.tensor(1000)
t1 = tor.tensor([1,2,3,5,6,7])
t2 = tor.tensor([[1,2,3],[7,8,5]])
print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([1, 2, 3, 5, 6, 7])
tensor([[1, 2, 3],
        [7, 8, 5]])


In [6]:
# change the dimension of tensor is
# Tensor.view(nrows,ncols)
#
#

In [7]:
from torch.autograd import Variable


In [8]:
x = Variable(torch.ones(2,2),requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [9]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [10]:
print(y.grad_fn)

In [11]:
z = y * y * 3
out = z.mean()

print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


### Gradient Calculation

In [12]:
import torch as tor
x = tor.rand(3,requires_grad=True)
print(x)

y = x + 2
print(y)

tensor([0.3038, 0.0710, 0.4154], requires_grad=True)
tensor([2.3038, 2.0710, 2.4154], grad_fn=<AddBackward0>)


In [13]:
z = y * y * 2
z

tensor([10.6154,  8.5777, 11.6680], grad_fn=<MulBackward0>)

In [14]:
#z = z.mean()
#z

In [15]:
# grad can be implicitly created only for scalar outputs
# z mean give us one value
#
# vector jocovian product learn

In [16]:
v = torch.tensor([0.1,1.0,0.001],dtype = torch.float32)

In [17]:
z.backward(v)


In [18]:
print(x.grad)

tensor([0.9215, 8.2838, 0.0097])


# NB
whenever _ in the end of fuctions which means its update the variable

In [19]:
# detch
import torch
x = torch.randn(3,requires_grad=True)
print(x)

y = x.detach()
y
# the output of Y is same as like the output of X but the missing is requires_grad=True
#
# which is a boolean value that determines whether or not gradients should be computed for the tensor.
# Gradients are used in backpropagation to update the weights of a neural network during training.
# By default, tensors in PyTorch have .requires_grad set to True.

tensor([-0.4366, -1.3632,  0.0206], requires_grad=True)


tensor([-0.4366, -1.3632,  0.0206])

## Forward and Backward propagation with Torch

In [20]:
# forward pass
import torch as tr

x = tr.tensor(1.0)
y = tr.tensor(2.0)

w = tr.tensor(1.0,requires_grad=True)

y_hat = w*x
loss = (y_hat - y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [21]:
#  backword pass
loss.backward()
print(w.grad)

tensor(-2.)


In [22]:
### update weights
# next forward and backwards
torch.device('cuda:0')

device(type='cuda', index=0)

In [23]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [24]:
x.stride()

(5, 1)

In [25]:
x.t().stride()

(1, 5)

In [26]:
# https://pytorch.org/docs/stable/nn.html#containers
#

### Manualy implemented
- numpy use

In [27]:
import numpy as np
# f = w * x
# f = 2 * x
x = np.array([1,2,3,4],dtype=np.float32)
y = np.array([2,4,6,8],dtype=np.float32)

w = 0.0
# model prediction
def forward(x):
  return w * x
# loss
def loss(y,y_predict):
  return ((y_predict - y)**2).mean()
# Gradient
# mse = 1/N * ( w*x - y)**2
# dz/dw = 1/N 2x(w*x-y)

def gradient(x,y,y_predict):
  return np.dot(2*x,y_predict-y).mean()

print(f'prediction before traning f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  y_pred  = forward(x)

  l= loss(y,y_pred)

  dw = gradient(x,y,y_pred)

  w -= learning_rate*dw

  if epoch%2 ==0:
    print(f'epoch = {epoch+1} w = {w:.3f} and loss = {l:.8f}')
print(f'prediction after traning f(5) = {forward(5):.3f}')

prediction before traning f(5) = 0.000
epoch = 1 w = 1.200 and loss = 30.00000000
epoch = 3 w = 1.872 and loss = 0.76800019
epoch = 5 w = 1.980 and loss = 0.01966083
epoch = 7 w = 1.997 and loss = 0.00050331
epoch = 9 w = 1.999 and loss = 0.00001288
epoch = 11 w = 2.000 and loss = 0.00000033
epoch = 13 w = 2.000 and loss = 0.00000001
epoch = 15 w = 2.000 and loss = 0.00000000
epoch = 17 w = 2.000 and loss = 0.00000000
epoch = 19 w = 2.000 and loss = 0.00000000
prediction after traning f(5) = 10.000


### Torch use

In [28]:
import torch as tr
# f = w * x
# f = 2 * x
x = tr.tensor([1,2,3,4],dtype=tr.float32)
y = tr.tensor([2,4,6,8],dtype=tr.float32)

w = tr.tensor(0.0,dtype=tr.float32,requires_grad=True)

# model prediction
def forward(x):
  return w * x

# loss
def loss(y,y_predict):
  return ((y_predict - y)**2).mean()

# Gradient
# mse = 1/N * ( w*x - y)**2
# dz/dw = 1/N 2x(w*x-y)

print(f'prediction before traning f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  y_pred  = forward(x)

  l= loss(y,y_pred)
  # backword
  l.backward()
  with tr.no_grad():
      w -= learning_rate*w.grad
  w.grad.zero_()

  if epoch%10 ==0:
    print(f'epoch = {epoch+1} w = {w:.3f} and loss = {l:.8f}')
print(f'prediction after traning f(5) = {forward(5):.3f}')

prediction before traning f(5) = 0.000
epoch = 1 w = 0.300 and loss = 30.00000000
epoch = 11 w = 1.665 and loss = 1.16278565
epoch = 21 w = 1.934 and loss = 0.04506890
epoch = 31 w = 1.987 and loss = 0.00174685
epoch = 41 w = 1.997 and loss = 0.00006770
epoch = 51 w = 1.999 and loss = 0.00000262
epoch = 61 w = 2.000 and loss = 0.00000010
epoch = 71 w = 2.000 and loss = 0.00000000
epoch = 81 w = 2.000 and loss = 0.00000000
epoch = 91 w = 2.000 and loss = 0.00000000
prediction after traning f(5) = 10.000


In [32]:
import torch.nn as nn
m = nn.Conv1d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50)
output = m(input)

In [34]:
output.shape

torch.Size([20, 33, 24])